const ProductData = [
  {
    id: 1,
    quantity: 1,
    title: 'DC Tshirt with Round Neck',
    img: require('../ProductsImage/Tshirt.jpg'),
    price: 25,
    colors: ['skyblue', 'darkred', 'grey', 'black', 'lightgrey'],
    categ: ['Men'],
    rating: 5,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
    inWishlist: false,
    details:
      'A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long',
  },
  {
    id: 2,
    quantity: 1,
    title: 'Jacket Full Sleeve Double Collar',
    img: require('../ProductsImage/Tshirt2.jpeg'),
    price: 30,
    colors: ['skyblue', 'tan', 'darkred', 'grey', 'black', 'gold'],
    categ: ['Men'],
    rating: 3,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
    inWishlist: false,
    details:
      'A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long',
  },
  {
    id: 3,
    quantity: 1,
    title: 'Plain Half Sleeve Tshirt',
    img: require('../ProductsImage/Tshirt3.jpg'),
    price: 5,
    colors: ['skyblue', 'tan', 'darkred', 'lightgreen'],
    categ: ['Men'],
    rating: 4,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
    inWishlist: false,
    details:
      'A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long',
  },
  {
    id: 4,
    quantity: 1,
    title: 'Stretchable Cotton Pants Side pockets',
    img: require('../ProductsImage/Pants1.jpg'),
    price: 18,
    colors: ['black', 'skyblue', 'rgb(253, 120, 45)'],
    categ: ['Men'],
    rating: 4,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
    inWishlist: false,
    details:
      'A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long',
  },
  {
    id: 5,
    quantity: 1,
    title: `Men's Formal Outfit with Coat`,
    img: require('../ProductsImage/Formal.jpg'),
    price: 49,
    colors: ['skyblue', 'violet', 'grey', 'black'],
    categ: ['Men'],
    rating: 1,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
    inWishlist: false,
    details:
      'A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long',
  },
  {
    id: 6,
    quantity: 1,
    title: `Men's Casual Outfit with Hoodie`,
    img: require('../ProductsImage/Casual.jpg'),
    price: 42,
    colors: ['black', 'white', 'grey'],
    categ: ['Men'],
    rating: 3,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
    inWishlist: false,
    details:
      'A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long',
  },
];

export default ProductData;
