// For Wishlist
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

// For Cart
export const ADD_INTO_CART = 'ADD_INTO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_ITEM_INTO_CART = 'ADD_ITEM_INTO_CART';
export const MIN_ITEM_INTO_CART = 'MIN_ITEM_INTO_CART';
export const SET_ITEM_QUANTITY = 'SET_ITEM_QUANTITY';

export const EMPTY_CART = 'EMPTY_CART';
