const ProductData = [
  {
    id: 1,
    title: 'DC Tshirt with Round Neck',
    img: require('../ProductsImage/Tshirt.jpg'),
    price: 25,
    colors: ['skyblue', 'tan', 'grey'],
    categ: ['top', 'kids'],
    rating: 5,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
  },
  {
    id: 2,
    title: 'Jacket Full Sleeve Double Collar',
    img: require('../ProductsImage/Tshirt2.jpeg'),
    price: 30,
    colors: ['skyblue', 'tan', 'grey'],
    categ: ['top', 'men'],
    rating: 3,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
  },
  {
    id: 3,
    title: 'Plain Half Sleeve Tshirt',
    img: require('../ProductsImage/Tshirt3.jpg'),
    price: 5,
    colors: ['skyblue', 'tan', 'grey'],
    categ: ['top', 'men'],
    rating: 4,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
  },
  {
    id: 4,
    title: 'Stretchable Cotton Pants Side pockets',
    img: require('../ProductsImage/Pants1.jpg'),
    price: 18,
    colors: ['skyblue', 'tan', 'grey'],
    categ: ['top', 'men'],
    rating: 4,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
  },
  {
    id: 5,
    title: `Men's Formal Outfit with Coat`,
    img: require('../ProductsImage/Formal.jpg'),
    price: 49,
    colors: ['skyblue', 'tan', 'grey'],
    categ: ['top', 'men'],
    rating: 1,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
  },
  {
    id: 6,
    title: `Men's Casual Outfit with Hoodie`,
    img: require('../ProductsImage/Casual.jpg'),
    price: 42,
    colors: ['skyblue', 'tan', 'grey'],
    categ: ['top', 'men'],
    rating: 3,
    size: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXL'],
  },
]

export default ProductData
